apiVersion: v1
kind: Pod
metadata:
  name: db
  labels: 
    app: db
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    env: 
     - name: POSTGRES_USER
       value: postgres
     - name: POSTGRES_PASSWD
       value: postgres  
    ports: 
     - containerPort: 5432
       name: postgres